spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uvpower
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: caffeine

file:
  upload-dir: uploads/


cloudinary:
  cloud-name: dm8pnq4dw
  api-key: 962186562481374
  api-secret: 9mUImCcIfTkaxn3mI1AAInSuAM8