spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.oqorepdnffxiqqgdthoy&password=Uvpower@2858
#    username: uv-power-db
#    password: your_database_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # change to validate in production
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

cloudinary:
  cloud-name: dm8pnq4dw
  api-key: 962186562481374
  api-secret: 9mUImCcIfTkaxn3mI1AAInSuAM8